version: '3.9'
services:
  cron:
    container_name: velog-cron
    build:
      context: ../../
      dockerfile: ./apps/cron/Dockerfile
      args:
        DOCKER_ENV: 'stage'
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    tty: true
    stdin_open: true
    ports:
      - 5004:5004
    deploy:
      resources:
        limits:
          cpus: '1' # range 0.01 to 10.00
          memory: '2G'
        reservations:
          cpus: '0.25'
          memory: '256M'
