version: '3.9'
services:
  server:
    build:
      context: ../../
      dockerfile: ./packages/velog-server/Dockerfile
      args:
        DOCKER_ENV: stage
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    env_file:
      - ../../.env
    tty: true
    stdin_open: true
    ports:
      - 5003:5003
    mem_limit: '1g'
