version: '3.9'
services:
  web:
    build:
      context: ../../
      dockerfile: ./packages/velog-web/Dockerfile
      args:
        DOCKER_ENV: stage
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    env_file:
      - ../../.env
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
