name: Velog Server build workflow

on:
  pull_request:
    branches: ['main', 'development', 'hotfix']
    paths:
      - 'packages/velog-cron/**'
      - '.github/workflows/velog-server-build.yml'
jobs:
  server-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.1]
    defaults:
      run:
        working-directory: './packages/velog-cron'

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm prisma:copy
      - run: npx prisma generate

      - run: pnpm ssm pull -e stage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: pnpm build
